version: '3'

services:
  app:
    image: eclipse-temurin:17
    ports:
      - 8080:8080
    working_dir: /app/target
    volumes:
      - ./target:/app/target
    command: ["java", "-jar", "kakei_track_api-0.0.1-SNAPSHOT.jar"]
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.26
    environment:
      MYSQL_DATABASE: kakei_track_database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
