version: '3'

services:
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.26
    environment:
      MYSQL_DATABASE: kakei_track_database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
